// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'firebase_options.dart';

/// // ...
//await Firebase.initializeApp(
// options: DefaultFirebaseOptions.currentPlatform,
//);
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9PJwDBxDuzdNEwg7fiE41aWCPdXdtN70',
    appId: '1:853180830174:web:7a236070764bd691e9cd4f',
    messagingSenderId: '853180830174',
    projectId: 'to-do-list-28fc4',
    authDomain: 'to-do-list-28fc4.firebaseapp.com',
    storageBucket: 'to-do-list-28fc4.appspot.com',
    measurementId: 'G-M0X4W53DB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGvvOuha9DX0ub0gm9gx5wSxUsXxm7Gx4',
    appId: '1:853180830174:android:36d2058d5da4289ce9cd4f',
    messagingSenderId: '853180830174',
    projectId: 'to-do-list-28fc4',
    storageBucket: 'to-do-list-28fc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJZAmNAL44DFjUwM1UQORnD6Zo35BbyJs',
    appId: '1:853180830174:ios:34f1d2f68c8c6c53e9cd4f',
    messagingSenderId: '853180830174',
    projectId: 'to-do-list-28fc4',
    storageBucket: 'to-do-list-28fc4.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJZAmNAL44DFjUwM1UQORnD6Zo35BbyJs',
    appId: '1:853180830174:ios:34f1d2f68c8c6c53e9cd4f',
    messagingSenderId: '853180830174',
    projectId: 'to-do-list-28fc4',
    storageBucket: 'to-do-list-28fc4.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9PJwDBxDuzdNEwg7fiE41aWCPdXdtN70',
    appId: '1:853180830174:web:a277dde9d44a692fe9cd4f',
    messagingSenderId: '853180830174',
    projectId: 'to-do-list-28fc4',
    authDomain: 'to-do-list-28fc4.firebaseapp.com',
    storageBucket: 'to-do-list-28fc4.appspot.com',
    measurementId: 'G-2LQZ43G21T',
  );
}
